max_width = 155
short_array_element_width_threshold = 155
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
fn_params_layout = "Compressed"
single_line_if_else_max_width = 155

# *** only available in unstable rust ***
where_single_line = true
fn_single_line = true
group_imports = "One"
condense_wildcard_suffixes = true
# ***************************************
